import Link from "next/link"

export const metadata = {
  title: {
    default:'Next js',
    template:'%s|codevolution'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding:'1rem' , backgroundColor:'lightblue' }} >
            <h1>Header</h1>
            <Link href={'/blog'} >Blog</Link>
            <Link href={'/products'} >Products</Link>
            <Link href={'/about'} >ABout</Link>
        </header>
        {children}
        <footer style={{ padding:'1rem' ,backgroundColor:'ghostwhite' }} >
            <h2>Footer</h2>
        </footer>
      </body>
    </html>
  )
}
